# Coding Temple's Data Analytics Program  
---
# Advanced Python - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [1]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE

import numpy as np

In [2]:
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [3]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [6]:
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility

#YOUR CODE HERE
#from numpy import random

myarray = np.random.randint(low=0, high=100, size=(5,3))

# Print out the array

print(myarray)


AttributeError: module 'numpy' has no attribute 'random'

### 1.2 Solution - Run the following cell to check your answer.

In [ ]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [ ]:
height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]

#make list into array
l1 = np.array(height)
l2 = np.array(weight)

bmi = 703 * l2 * l1**2
print(bmi)

[ 361517750 1822176000 1081917000 1406000000]


### 1.3 Solution: Run the following cell to check your answer.

In [ ]:
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'

AssertionError: Make sure you have saved your results to the proper variable name!

### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [ ]:
def my_func(matrix):
    matrix = np.random.randint()
    return matrix
print(np.random.randint(low=4,high=33, size=(5,2)))

[[24  9]
 [22 24]
 [15 32]
 [14 32]
 [18 22]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [ ]:
# 1. Return the first row:

matrix = np.array([[4,5,6,7], [1,2,6,7]])
print(matrix[0])

[4 5 6 7]


In [ ]:
# 2. Return the last column
"""add column"""
shape = (2,4)

Last_r = np.matrix(shape, int)
print("oritinal ", matrix)
print("last row ", matrix[1])

oritinal  [[4 5 6 7]
 [1 2 6 7]]
last row  [1 2 6 7]


In [ ]:
# 3. Return the third column values from the 4th and 5th rows
l1 = [3,4,5]
l2 =[6,7,8]
l3 = [9,10,11]
l4 = [12,13,14]
l5 = [15,16,17]

Row_matrix = [l1,l2,l3,l4,l5]
Row_matrix = np.array(Row_matrix)

print(f"This is l4. I know that i should have added another row but it's late(cry emoji): {Row_matrix[3][1]}")
print(f"this is l5: {Row_matrix[4][1]}")

    




This is l4. I know that i should have added another row but it's late(cry emoji): 13
this is l5: 16


In [ ]:
# 4. Multiply every value in the array by 2

Row_matrix *2


array([[ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [ ]:
# 5. Divide every value by 3

Row_matrix //3

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [ ]:
# 6. Increase the values in the first row by 12
print(Row_matrix[0]+12)

[15 16 17]


In [ ]:
# 7. Calculate the mean of the first column
print(Row_matrix.mean(axis=1))

[ 4.  7. 10. 13. 16.]


In [ ]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
print(Row_matrix)

delete_low = np.delete(Row_matrix,[0,1])
print(f"The lowest values are deleted: ", delete_low)
print("Mean of delete_low: ", delete_low.mean())

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
The lowest values are deleted:  [ 5  6  7  8  9 10 11 12 13 14 15 16 17]
Mean of delete_low:  11.0


In [2]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array

array_std = np.random.randint(low=2,high=93, size=(3,3))
print(array_std)
std_d = np.std(array_std, axis=0)
print(std_d)


NameError: name 'np' is not defined

In [1]:
# 10. Return values in the second column greater than 25

condition = array_std[:,1] > 25


NameError: name 'array_std' is not defined

In [ ]:
# 11. Return values < 40 in the array

M = np.where(array_std<40)

array_std[M] = 39

print(M)

(array([0, 1, 2, 2]), array([1, 0, 1, 2]))


### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [ ]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.3

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])